### ISSUE TITLE
Static dependency into Swift project

### ISSUE THREAD

**Issue by ldi13** [NicePeopleAtWork/Youbora-AVPlayer-iOS#1]
Hi Youbora team,

I am Lorenzo, iOS developer at Molotov.
We are currently trying to implement your solution for video monitoring, and we are facing a problem during the integration.

We'd like to wrap your dependencies into a private podspec in order for it to be reusable for iOS & tvOS, with only one depency called MolotovYoubora.

When I add the dependency 'Youbora-AVPlayer' into the podspec, I get the following error:

```
-> Using Youbora-AVPlayer (5.3.3)

-> Using Youbora-YouboraLib (5.3.6)
  - Running pre install hooks
[!] The 'Pods-MolotovYoubora_Tests' target has transitive dependencies that include static
binaries: (/Users/ldivita/Pods/ios-molotov-youbora/Example/Pods/Youbora-AVPlayer/ios/YouboraPluginAVPlayer.framework)
```

The YouboraLib seems to wrap a static binary inside its framework's dependencies, but that's not allowed for cocoapods project using frameworks only (Swift projects with the flag use_frameworks! declared inside the Podfile).

Do you have any support to provide regarding this issue ?
Thank you,

Best regards,

Lorenzo.

**Comment by jtreveset-nice** [comment]
Hi Lorenzo,

I'm glad to tell you that we've updated our AVPlayer plugin and YouboraLib pods now containing a dynamic subspec.

You should be able to use it with the following dependency in your podspec file.

`pod 'Youbora-AVPlayer/dynamic'`

If you don't specify the subspec it will default to the static one.

Regards,

Joan
