### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by thomalexandre** [NicePeopleAtWork/Youbora-AVPlayer-iOS#2]
Hi
Could you point to the installation steps, and how to configure the library
The Readme.md file is empty at the moment
Alex

**Comment by jtreveset-nice** [comment]
Hi Alex,

You can see how to install and use the library from our developer portal; http://developer.nicepeopleatwork.com/

Please contact our Customer Engineering team if you have any doubts or need access to it. You can reach them at engineering (at) nicepeopleatwork.com

Thanks!
